#!/bin/bash
apt-get -y install git
apt-get -y install wget
apt-get -y install python-opencv
apt-get -y install python-numpy
apt-get -y install python-posix-ipc
apt-get -y install python-pip
apt-get -y install python-virtualenv
apt-get -y install python-matplotlib
apt-get -y install python-boto
apt-get -y install cython
apt-get -y install python-scipy
apt-get -y install python-sphinx
apt-get -y install python-pytest
apt-get -y install libcv-dev
apt-get -y install libhighgui-dev
apt-get -y install libboost-python-dev
apt-get -y install gcc
apt-get -y install g++
apt-get -y install libeigen3-dev
apt-get -y install libopencv-dev
